# .github/workflows/upload_music.yml (已修复初始化问题)

name: Upload Music and Update Library

on:
  repository_dispatch:
    types: [upload-music]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Decode and write music file
        env:
          FILENAME: ${{ github.event.client_payload.filename }}
          FILE_CONTENT_BASE64: ${{ github.event.client_payload.content }}
        run: |
          echo "Writing to file: uploads/music/${FILENAME}"
          mkdir -p uploads/music
          echo "${FILE_CONTENT_BASE64}" | base64 --decode > "uploads/music/${FILENAME}"

      - name: Update library.json
        env:
          FILENAME: ${{ github.event.client_payload.filename }}
          TITLE: ${{ github.event.client_payload.title }}
          SINGERS_JSON: ${{ toJSON(github.event.client_payload.singers) }}
          ORIGINAL: ${{ github.event.client_payload.original }}
        run: |
          echo "Updating library.json with new song: ${TITLE}"
          
          # 【关键修复】: 检查 library.json 是否存在，如果不存在，则创建一个包含空数组的文件。
          if [ ! -f library.json ]; then
            echo "library.json not found. Creating a new one."
            echo "[]" > library.json
          fi
          
          # 创建新的歌曲条目 JSON 对象
          NEW_SONG_ENTRY=$(jq -n \
            --argjson id "$(date +%s%3N)" \
            --arg title "$TITLE" \
            --argjson singers "$SINGERS_JSON" \
            --arg original "$ORIGINAL" \
            --arg file "$FILENAME" \
            '{id: ($id | tonumber), title: $title, singers: $singers, original: $original, file: $file}')

          # 将新条目追加到 JSON 数组中
          jq ". + [$NEW_SONG_ENTRY]" library.json > library.json.tmp && mv library.json.tmp library.json
          
          echo "Updated library.json content:"
          cat library.json

      - name: Commit and push changes
        env:
          TITLE: ${{ github.event.client_payload.title }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          # 同时添加音乐文件和 library.json
          git add "uploads/music/${{ github.event.client_payload.filename }}" library.json
          
          # 检查是否有文件变动，只有在有变动时才提交
          if ! git diff-index --quiet HEAD; then
            git commit -m "feat: Add new music '${TITLE}' and update library"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
